spring.application.name=todo-backend

server.address=0.0.0.0
server.port=${PORT:8080}

# Local PostgreSQL database for Android emulator/backend testing.
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:kzDiUcMLsuNN1TqxXLVZ2MxSK0q3PBmFHnWy9kNs4Ny}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3153600000000}

app.reset.otp-expiration-minutes=${OTP_EXPIRATION_MINUTES:5}

# Gmail SMTP config for password reset OTP.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tranhoang411543@gmail.com
spring.mail.password=qhxr rekx kaos tygg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
